#端口号
server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true               #开启服务注册和发现的功能，自动创建router以服务名开头的请求路径转发到对应的服务
          lowerCaseServiceId: true    #将请求路径上的服务名配置为小写
#      routes:
#        # 将请求路径以/consumer/**的请求全部转发到service-consumer服务
#        - id: student # 路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://student-service # 匹配后提供服务的路由地址, lb代表从注册中心获取服务
#          predicates: # 断言
#            - Path=/student/** #路径相匹配的进行路由转发; 【访问 /xxx/** 时会自动转发到 xxx-service 服务】
#          filters:
#            - StripPrefix=1 # 过滤器，去掉请求路径的第一个路径
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"   # 允许那些网站的跨域请求
            allowedMethods: "*"   # 允许的跨域ajax的请求方式
            allowedHeaders: "*"   # 允许在请求中携带的头信息