server:
  port: 9010
spring:
  application:
    name: other-service          #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #nacos服务地址
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
# 自定义配置
tce:
  qiniu:
    ak: 5D-6A4aW5hpxmha3DpQC0nTfahnfjMtd95NtcZOJ
    sk: 6DdNoOiuzTJUHtnUKo4rHRRNsLhiG9pSxdnmHFpq
    bucket: tockey
    baseUrl: https://img.tockey.cn/
    path: gp/
